# Site settings é…ç½®ç«™ç‚¹
title: "JingChao's Party"
description: 'your web description'
keywords: 'your web keywords, another keywords'
#url: 'https://abc.github.io' # your host
url: 'https://jingchao.org.cn' # your host

# nav ä¸­æ–‡å­—ç¬¦ç©ºæ ¼ï¼š&emsp;
nav: # æœ€ä½³ä½“éªŒ å…­ä¸ªæ ‡ç­¾ ä¸”æœ€å¥½æ¯ä¸ªæ ‡ç­¾ä¸è¶…è¿‡4ä¸­æ–‡å­—
  home: '/'
  tags: '/tags.html'
  timeline: '/timeline.html'
  about: '/about.html'
  links: '/friendLink.html'

# åšä¸»
author: true
name: 'Jingchao'
NickName: 'æ™¯è¶…'
webtitle: 'Jingchao'
bio: 'è¿˜æ˜¯å°‘å¹´...å—'
about: true
aboutyou: 'è¿™ä¸æ˜¯ä½œä¸šæœ¬ï¼Œè€Œæ˜¯ä»–ä¹±å†™ä¹±ç”»çš„åœ°æ–¹ã€‚æœ‰æ„è§çš„æ”¾å­¦åˆ«èµ°ï¼Œå¯ä»¥ä¸‹é¢æ‰¾æˆ‘ğŸ‘‡ å“ˆå“ˆå“ˆå“ˆ'
portraits: '/assets/img/chenjingchao.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['facebook', 'weibo', 'QQ', 'github', 'Dribbble', 'twitter', 'instagram', 'weixin']
  mail: 'mailto:alfred.chen007@gmail.com'
  weixin: 'http://pdsw7h3kf.bkt.clouddn.com/2018-08-31-1331535702513_.pic.jpg' # your wechat image file path
  QQ: 'http://pdsw7h3kf.bkt.clouddn.com/2018-08-31-1341535702950_.pic.jpg' # your QQ image file path
  weibo: 'https://weibo.com/carlybb'
  #instagram: ''
  #twitter: ''
  github: ''
  #Dribbble: ''
  #facebook: ''
  #Google: ''
  zhihu: ''
  juejin: ''
  #twitch: ''

# åˆ†é¡µ
paginate: 4
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# ä»£ç é«˜äº® ä½¿ç”¨rouge
highlighter: rouge
# ä»£ç é«˜äº®ä¸»é¢˜ä½¿ç”¨pygmentsä¸»é¢˜: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango ä»»é€‰ä¸€ä¸ªä½ å–œæ¬¢çš„ä¸»é¢˜åç§°å¡«åœ¨ä¸‹é¢çš„å•å¼•å·ä¸­
pygmentsTheme: 'default'

# å‹æƒ…é“¾æ¥
friends:
  Jangwooning: 'https://guangningsun.github.io/'

# è¯„è®º æœ€ä½³ä½“éªŒ åœ¨disqusã€livereå’ŒGitmentä¹‹é—´ä¸‰é€‰ä¸€
# disqus è¯„è®º
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# æ¥å¿…åŠ›è¯„è®º
livere: true
livere_uid: 'MTAyMC8zOTM5MC8xNTkxNw==' # 
# Gitmentè¯„è®º OAuth Application
Gitment: false
Gitment_owner: ''  # githubç”¨æˆ·å
Gitment_repo: ''  # githubåšå®¢å­˜æ”¾çš„ä»“åº“å
client_id: ''  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_id
client_secret: ''  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: false
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# ç™¾åº¦ç»Ÿè®¡ åœ¨baidu-urlé‡Œå¡«å†™è‡ªå·±ç›¸å…³çš„urlä»£ç 
baidu: true
baidu-url: ''
# è°·æ­Œåˆ†æ åœ¨google-IDé‡Œå¡«å†™è‡ªå·±åœ¨è°·æ­Œåˆ†æè·å¾—çš„è¿½è¸ªID
google: false
google-ID: ''

# åšå®¢å¤´ä¿¡æ¯å¤‡é€‰é¢œè‰²ï¼ˆè¯¥éƒ¨åˆ†åœ¨ç«™ç‚¹ä¸­ä¸å……å½“ç«™ç‚¹å˜é‡ï¼Œå°†å…¶å†™åœ¨postçš„å¤´ä¿¡æ¯ä¸­ç”¨æ¥å……å½“é¡µé¢å˜é‡ï¼‰
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
